package com.google.code.jcbir.gui;

import com.birosoft.liquid.LiquidLookAndFeel;
import com.google.code.jcbir.Constants;
import com.google.code.jcbir.clustering.Cluster;
import com.google.code.jcbir.clustering.KMeans;
import com.google.code.jcbir.indexing.ClusterReader;
import com.google.code.jcbir.indexing.ClusterWriter;
import com.google.code.jcbir.indexing.Index;
import com.google.code.jcbir.indexing.IndexReader;
import com.google.code.jcbir.indexing.IndexWriter;
import com.google.code.jcbir.search.ImageResult;
import com.google.code.jcbir.search.ImageSearcher;
import com.google.code.jcbir.util.GraphicsUtilities;
import com.google.code.jcbir.util.ImageFileFilter;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.SwingWorker;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author eadams
 * @author denny
 */
public class MainFrame extends javax.swing.JFrame {

    private JFileChooser folderChooser = new JFileChooser();
    private JFileChooser imageChooser = new JFileChooser();
    private SwingWorker<List<ImageResult>, ImageResult> searchWorker;
    private SwingWorker<String, Void> indexWorker;
    private SwingWorker<String, Void> browseWorker;
    private long time;
    private int numIndex;
    //new
     private final JFileChooser imageChooser1 = new JFileChooser();
     BufferedImage bufferedImage1;
     int height;
     int width;
     String gender;
     String hair;
     String gender1;
     String hair1;
     File f;
     String path;
     FileInputStream fis;
    
    //end

    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        try {
            inititalizeIndexBrowser();
        } catch (IOException ex) {
            browsePanel.setVisible(false);

        }
    }

    private void inititalizeIndexBrowser() throws IOException {
        IndexReader indexReader = new IndexReader();
        indexReader.open();
        int clustSize = indexReader.numCluster();
        indexReader.close();
        if (clustSize < 2) {
            browsePanel.setVisible(false);
            return;
        }


        //enabled clustId combobox
        Integer[] nums = new Integer[clustSize];
        for (int i = 0; i < clustSize; i++) {
            nums[i] = i + 1;
        }

        thumbIndexPanel.getListModel().clear();
        clustIdComboBox.setModel(new DefaultComboBoxModel(nums));
        browsePanel.setVisible(true);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        cbirTab = new javax.swing.JTabbedPane();
        searchTab = new javax.swing.JPanel();
        queryPanel = new javax.swing.JPanel();
        imagePathText = new javax.swing.JTextField();
        browseButton = new javax.swing.JButton();
        searchButton = new javax.swing.JButton();
        imagePanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        betaLabel1 = new javax.swing.JLabel();
        betaText = new javax.swing.JTextField();
        alphaLabel1 = new javax.swing.JLabel();
        alphaText = new javax.swing.JTextField();
        useClusterCheck = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        resultPanel = new javax.swing.JPanel();
        searchProgress = new javax.swing.JProgressBar();
        statusLabel = new javax.swing.JLabel();
        thumbnailPanel = new com.google.code.jcbir.gui.JThumbnailPanel();
        indexingTab = new javax.swing.JPanel();
        folderPanel = new javax.swing.JPanel();
        folderText = new javax.swing.JTextField();
        browseFolderButton = new javax.swing.JButton();
        startIndexButton = new javax.swing.JButton();
        numClusterLabel = new javax.swing.JLabel();
        numClusterCombo = new javax.swing.JComboBox();
        maxIterLabel = new javax.swing.JLabel();
        maxIterText = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        progressPanel = new javax.swing.JPanel();
        indexProgress = new javax.swing.JProgressBar();
        indexingStatusLabel = new javax.swing.JLabel();
        browsePanel = new javax.swing.JPanel();
        browseIndexProgress = new javax.swing.JProgressBar();
        browseIndexLabel = new javax.swing.JLabel();
        thumbIndexPanel = new com.google.code.jcbir.gui.JThumbnailPanel();
        selectClusterLabel = new javax.swing.JLabel();
        clustIdComboBox = new javax.swing.JComboBox();
        viewDataButton = new javax.swing.JButton();
        aboutTab = new javax.swing.JPanel();
        creditsPanel = new javax.swing.JPanel();
        luceneLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Gender = new java.awt.Label();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jLabel5.setText("Similarity Treshold :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JCBIR - Java Content Based Image Retrieval");

        queryPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Images"));

        imagePathText.setEditable(false);

        browseButton.setText("Browse ...");
        browseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseButtonActionPerformed(evt);
            }
        });

        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchButton.setForeground(new java.awt.Color(102, 102, 102));
        searchButton.setText("Search");
        searchButton.setEnabled(false);
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        imagePanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        imagePanel.setPreferredSize(new java.awt.Dimension(128, 28));
        imagePanel.setLayout(new java.awt.BorderLayout());
        imagePanel.add(imageLabel, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        betaLabel1.setText("Rough filtering const");

        betaText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        betaText.setText("0.2");
        betaText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                betaTextCaretUpdate(evt);
            }
        });

        alphaLabel1.setText("Precise Filtering Treshold");

        alphaText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        alphaText.setText("0.3");
        alphaText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                alphaTextCaretUpdate(evt);
            }
        });

        useClusterCheck.setSelected(true);
        useClusterCheck.setText("K-Means");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(betaLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(betaText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(alphaLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alphaText, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(useClusterCheck))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(betaLabel1)
                .addComponent(betaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(alphaLabel1)
                .addComponent(alphaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(useClusterCheck))
        );

        jLabel2.setText("Image Tracking");

        javax.swing.GroupLayout queryPanelLayout = new javax.swing.GroupLayout(queryPanel);
        queryPanel.setLayout(queryPanelLayout);
        queryPanelLayout.setHorizontalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(queryPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(queryPanelLayout.createSequentialGroup()
                                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, queryPanelLayout.createSequentialGroup()
                                .addComponent(imagePathText, javax.swing.GroupLayout.DEFAULT_SIZE, 1035, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(browseButton)))
                        .addContainerGap())
                    .addGroup(queryPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        queryPanelLayout.setVerticalGroup(
            queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
            .addGroup(queryPanelLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(imagePathText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(queryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        resultPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Result"));

        statusLabel.setText("Done ...");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thumbnailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1274, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                        .addComponent(statusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchProgress, javax.swing.GroupLayout.DEFAULT_SIZE, 1028, Short.MAX_VALUE)))
                .addContainerGap())
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(thumbnailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(searchProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statusLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout searchTabLayout = new javax.swing.GroupLayout(searchTab);
        searchTab.setLayout(searchTabLayout);
        searchTabLayout.setHorizontalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(queryPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        searchTabLayout.setVerticalGroup(
            searchTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(queryPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbirTab.addTab("Search", searchTab);

        folderPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Indexing Path"));

        folderText.setEditable(false);

        browseFolderButton.setText("Browse ...");
        browseFolderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseFolderButtonActionPerformed(evt);
            }
        });

        startIndexButton.setText("Start Indexing");
        startIndexButton.setEnabled(false);
        startIndexButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startIndexButtonActionPerformed(evt);
            }
        });

        numClusterLabel.setText("Number of Clusters : ");

        numClusterCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1" }));
        numClusterCombo.setEnabled(false);
        numClusterCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numClusterComboActionPerformed(evt);
            }
        });

        maxIterLabel.setText("Maximum Iteration :");

        maxIterText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        maxIterText.setText("200");
        maxIterText.setEnabled(false);
        maxIterText.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                maxIterTextCaretUpdate(evt);
            }
        });

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown" }));

        jButton3.setText("Retrieve");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setText("Enhanced Retrieval With Human Attribute");

        jButton4.setText("Delete db");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Start indexing");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout folderPanelLayout = new javax.swing.GroupLayout(folderPanel);
        folderPanel.setLayout(folderPanelLayout);
        folderPanelLayout.setHorizontalGroup(
            folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(folderPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addComponent(folderText, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(browseFolderButton))
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addComponent(startIndexButton)
                        .addGap(18, 18, 18)
                        .addComponent(numClusterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(numClusterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(maxIterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(maxIterText, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel7))
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(22, 22, 22)
                        .addComponent(jButton5)
                        .addGap(9, 9, 9)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        folderPanelLayout.setVerticalGroup(
            folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(folderPanelLayout.createSequentialGroup()
                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(folderPanelLayout.createSequentialGroup()
                        .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(folderPanelLayout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, folderPanelLayout.createSequentialGroup()
                                .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(folderText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(browseFolderButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3)
                            .addComponent(jButton4)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5)
                            .addComponent(startIndexButton)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, folderPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(numClusterLabel)
                        .addComponent(numClusterCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(maxIterLabel)
                        .addComponent(maxIterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        progressPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Indexing Progress"));

        javax.swing.GroupLayout progressPanelLayout = new javax.swing.GroupLayout(progressPanel);
        progressPanel.setLayout(progressPanelLayout);
        progressPanelLayout.setHorizontalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(indexingStatusLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(indexProgress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        progressPanelLayout.setVerticalGroup(
            progressPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(progressPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(indexProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(indexingStatusLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 18, Short.MAX_VALUE))
        );

        browsePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Browse Indexs"));

        browseIndexLabel.setText("Done ...");

        selectClusterLabel.setText("Select Cluster : ");

        clustIdComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2" }));

        viewDataButton.setText("View Data");
        viewDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDataButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout browsePanelLayout = new javax.swing.GroupLayout(browsePanel);
        browsePanel.setLayout(browsePanelLayout);
        browsePanelLayout.setHorizontalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(thumbIndexPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(browsePanelLayout.createSequentialGroup()
                        .addComponent(browseIndexLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseIndexProgress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, browsePanelLayout.createSequentialGroup()
                        .addComponent(selectClusterLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clustIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(viewDataButton)))
                .addContainerGap())
        );
        browsePanelLayout.setVerticalGroup(
            browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, browsePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selectClusterLabel)
                    .addComponent(clustIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewDataButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(thumbIndexPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addGap(7, 7, 7)
                .addGroup(browsePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browseIndexProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseIndexLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout indexingTabLayout = new javax.swing.GroupLayout(indexingTab);
        indexingTab.setLayout(indexingTabLayout);
        indexingTabLayout.setHorizontalGroup(
            indexingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, indexingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(indexingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(browsePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(progressPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(folderPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        indexingTabLayout.setVerticalGroup(
            indexingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(indexingTabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(folderPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(progressPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(browsePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        cbirTab.addTab("Indexing", indexingTab);

        creditsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        luceneLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/java.png"))); // NOI18N

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Browse..");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Male", "Female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Hair Color :");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select", "Black", "Brown" }));
        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Upload Image :");

        Gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Gender.setText("Gender :");

        javax.swing.GroupLayout creditsPanelLayout = new javax.swing.GroupLayout(creditsPanel);
        creditsPanel.setLayout(creditsPanelLayout);
        creditsPanelLayout.setHorizontalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(luceneLabel1)
                .addContainerGap())
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(creditsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, creditsPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        creditsPanelLayout.setVerticalGroup(
            creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(creditsPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(creditsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 276, Short.MAX_VALUE)
                .addComponent(luceneLabel1)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout aboutTabLayout = new javax.swing.GroupLayout(aboutTab);
        aboutTab.setLayout(aboutTabLayout);
        aboutTabLayout.setHorizontalGroup(
            aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, aboutTabLayout.createSequentialGroup()
                .addComponent(creditsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
        );
        aboutTabLayout.setVerticalGroup(
            aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(creditsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(aboutTabLayout.createSequentialGroup()
                .addGroup(aboutTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(aboutTabLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(aboutTabLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cbirTab.addTab("Attributes", aboutTab);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbirTab))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbirTab)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void browseFolderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseFolderButtonActionPerformed
        folderChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        folderChooser.setDialogTitle("Open Index Folder ...");
        folderChooser.showDialog(this, "Open");
        File f = folderChooser.getSelectedFile();
        if (f == null) {
            startIndexButton.setEnabled(false);
            numClusterCombo.setEnabled(false);
            maxIterText.setEnabled(false);
            return;
        }
        folderText.setText(f.getAbsolutePath());
        startIndexButton.setEnabled(true);


        File[] files = f.listFiles(new ImageFileFilter(false));
        if (files.length == 0) {
            return;
        }

        //enabled numCluster combobox
        int numOpt = (files.length / 2) - 1;
        Integer[] nums = new Integer[numOpt];
        for (int i = 0, j = 2; i < numOpt; j++, i++) {
            nums[i] = j;
        }


        numClusterCombo.setModel(new DefaultComboBoxModel(nums));
        numClusterCombo.setEnabled(true);
        maxIterText.setEnabled(true);


    }//GEN-LAST:event_browseFolderButtonActionPerformed

    private void startIndexButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startIndexButtonActionPerformed
        indexWorker = new SwingWorker<String, Void>() {

            String notes;

            @Override
            protected String doInBackground() throws Exception {
                File folder = folderChooser.getSelectedFile();
                // image filter masih nge-bug
                File[] files = folder.listFiles(new ImageFileFilter(false));
                //System.out.println(files.length);
                if (!folder.isDirectory() || folder == null || files.length == 0) {
                    notes = "FAIL";
                    return notes;
                }

                startIndexButton.setEnabled(false);
                viewDataButton.setEnabled(false);
                indexProgress.setStringPainted(true);
                time = System.currentTimeMillis();
                IndexWriter indexWriter = new IndexWriter();
                List<Index> indexes = new ArrayList<Index>();
                // feature extraction
                numIndex = 1;
                for (File f : files) {
                    try {
                        BufferedImage bufferedImage = ImageIO.read(f);
                        if (bufferedImage.getHeight(null) != Constants.IMAGE_HEIGHT
                                || bufferedImage.getWidth(null) != Constants.IMAGE_WIDTH) {
                            bufferedImage = GraphicsUtilities.resizeImage(bufferedImage,
                                    Constants.IMAGE_WIDTH, Constants.IMAGE_HEIGHT);
                        }
                        indexingStatusLabel.setText("Extracting image : " + f.getAbsolutePath());
                        Index index = indexWriter.getIndex(bufferedImage);
                        indexProgress.setValue(numIndex * 100 / files.length);
                        index.setFilePath(f.getAbsolutePath());
                        //indexWriter.addIndex(index);
                        indexes.add(index);
                        numIndex++;
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }

                // k-means clustering
                KMeans kMeans = new KMeans();
                int maxIter = Integer.parseInt(maxIterText.getText());
                kMeans.setNumCluster(Integer.parseInt(numClusterCombo.getSelectedItem().toString()));
                kMeans.setMaxIteration(maxIter);
                indexingStatusLabel.setText("Clustering Indexs ....");
                indexProgress.setIndeterminate(true);
                kMeans.computeCluster(indexWriter, indexes);
                indexProgress.setIndeterminate(false);

                indexingStatusLabel.setText("Saving Indexs ....");
                // indexing ...
                Cluster[] clusters = kMeans.getClusters();
                // create root index
                indexWriter.open();
                for (Cluster c : clusters) {
                    indexWriter.addCluster(c);
                }
                indexWriter.close();


                //create clusters index
                numIndex = 1;
                ClusterWriter clusterWriter = new ClusterWriter();
                for (int idx = 0; idx < kMeans.getNumCluster(); idx++) {
                    clusterWriter.open(idx);
                    for (Index ix : clusters[idx].getMembers()) {
                        indexingStatusLabel.setText("Add image " + ix.getFilePath() + " to cluster-" + idx);
                        clusterWriter.addIndex(ix);
                        indexProgress.setValue(numIndex * 100 / files.length);
                        numIndex++;
                    }
                    clusterWriter.close();
                }

                notes = "SUCCESS";
                return notes;
            }

            @Override
            protected void done() {
                indexProgress.setValue(0);
                if ("FAIL".equals(notes)) {
                    indexingStatusLabel.setText("Can't Index images because path has no images");
                    browsePanel.setVisible(false);
                    return;
                }
                indexingStatusLabel.setText("Finished indexing " + (numIndex - 1) + " images in " + ((System.currentTimeMillis() - time) / 1000) + " s.");
                //enabled clustId combobox
                Integer clustSize = (Integer) numClusterCombo.getSelectedItem();
                Integer[] nums = new Integer[clustSize];
                for (int i = 0; i < clustSize; i++) {
                    nums[i] = i + 1;
                }

                thumbIndexPanel.getListModel().clear();
                clustIdComboBox.setModel(new DefaultComboBoxModel(nums));
                browsePanel.setVisible(true);
                //thumbIndexPanel.setVisible(false);
                startIndexButton.setEnabled(true);
                viewDataButton.setEnabled(true);
            }
        };

        indexWorker.execute();
        /**
        // TODO add your handling code here:
        ImageIndexer indexer = new ImageIndexer();
        startIndexButton.setEnabled(false);
        try {
        indexer.indexToDatabase(folderChooser.getSelectedFile(), !addCheck.isSelected());
        } catch (Exception e) {
        }
        startIndexButton.setEnabled(true);*/
    }//GEN-LAST:event_startIndexButtonActionPerformed

    private void browseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseButtonActionPerformed
        try {
            imageChooser.setFileFilter(new ImageFileFilter());
            imageChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
            imageChooser.setDialogTitle("Open Query Image ...");
            imageChooser.showDialog(this, "Open");
            File f = imageChooser.getSelectedFile();
            if (f == null) {
                return;
            }
            imagePathText.setText(f.getAbsolutePath());
            BufferedImage bufferedImage = ImageIO.read(imageChooser.getSelectedFile());
            bufferedImage = GraphicsUtilities.resizeImage(bufferedImage, 125, 140);
            imageLabel.setIcon(new ImageIcon(bufferedImage));

        } catch (IOException ex) {
            ex.printStackTrace();
        }
        checkInputSearch();

    }//GEN-LAST:event_browseButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // check
        searchWorker = new SwingWorker<List<ImageResult>, ImageResult>() {

            @Override
            protected List<ImageResult> doInBackground() throws Exception {
                thumbnailPanel.setEnabled(false);
                ImageSearcher searcher = new ImageSearcher();
                BufferedImage bufferedImage = ImageIO.read(imageChooser.getSelectedFile());
                if (bufferedImage.getHeight(null) != Constants.IMAGE_HEIGHT
                        || bufferedImage.getWidth(null) != Constants.IMAGE_WIDTH) {
                    bufferedImage = GraphicsUtilities.resizeImage(bufferedImage,
                            Constants.IMAGE_WIDTH, Constants.IMAGE_HEIGHT);
                }
                time = System.currentTimeMillis();
                searchProgress.setIndeterminate(true);
                statusLabel.setText("Search Images ...");
                List<ImageResult> r = searcher.search(bufferedImage, Double.parseDouble(alphaText.getText()),
                        Double.parseDouble(betaText.getText()), useClusterCheck.isSelected());
                //System.out.println(r.size());
                return r;
            }

            @Override
            protected void done() {
                try {
                    thumbnailPanel.getListModel().clear();
                    List<ImageResult> r = get();
                    System.out.println("r = "+r.size());
                    searchProgress.setIndeterminate(false);
                    if (r.isEmpty()) {
                        thumbnailPanel.changePageButtonState();
                        statusLabel.setText("No images found ...");
                    } else {
                        thumbnailPanel.getListModel().setPageOffset(0);
                        
//                        for(int i=1;i<r.size()-4;i++)
  //                      {
    //                        r.remove(i);
      //                  }
                        
                        

                        System.out.println("r1 = "+r.size());
                        thumbnailPanel.getListModel().add(r);
                        thumbnailPanel.changePageButtonState();
                        statusLabel.setText("Finished in " + ((double) (System.currentTimeMillis() - time) / 1000) + " s.");
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                    searchProgress.setIndeterminate(false);
                    statusLabel.setText("Can't search images. Please do indexing ...");
                } finally {
                    thumbnailPanel.setEnabled(true);
                }
            }
        };


        searchWorker.execute();
        /**
        try {
        ImageSearcher searcher = new ImageSearcher();
        BufferedImage bufferedImage = ImageIO.read(imageChooser.getSelectedFile());
        if (bufferedImage.getHeight(null) != Constants.IMAGE_HEIGHT
        || bufferedImage.getWidth(null) != Constants.IMAGE_WIDTH) {
        bufferedImage = GraphicsUtilities.createCompatibleImage(bufferedImage,
        Constants.IMAGE_WIDTH, Constants.IMAGE_HEIGHT);
        }
        List<ImageResult> r = searcher.search(bufferedImage, 0.3, 0.5);
        thumbnailPanel.getListModel().clear();
        thumbnailPanel.getListModel().add(r);
        thumbnailPanel.changePageButtonState();
        } catch (IOException ex) {
        }*/
    }//GEN-LAST:event_searchButtonActionPerformed

    private void betaTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_betaTextCaretUpdate

        checkInputSearch();
    }//GEN-LAST:event_betaTextCaretUpdate

    private void alphaTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_alphaTextCaretUpdate
        checkInputSearch();
    }//GEN-LAST:event_alphaTextCaretUpdate

    private void maxIterTextCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_maxIterTextCaretUpdate
        // TODO add your handling code here:
        try {
            int maxIter = Integer.parseInt(maxIterText.getText());
            if (maxIter < 1) {
                startIndexButton.setEnabled(false);
                return;
            }

        } catch (NumberFormatException nfe) {
            startIndexButton.setEnabled(false);
            return;
        }

        startIndexButton.setEnabled(true);
    }//GEN-LAST:event_maxIterTextCaretUpdate

    private void viewDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDataButtonActionPerformed
        browseWorker = new SwingWorker<String, Void>() {

            @Override
            protected String doInBackground() throws Exception {

                try {
                    thumbIndexPanel.setEnabled(false);
                    viewDataButton.setEnabled(false);
                    //thumbIndexPanel.changePageButtonState();
                    thumbIndexPanel.getListModel().setPageOffset(0);
                    thumbIndexPanel.getListModel().clear();
                    Integer clustId = (Integer) clustIdComboBox.getSelectedItem() - 1;
                    IndexReader indexReader = new IndexReader();
                    indexReader.open();
                    Cluster selectedCluster = indexReader.getCluster(clustId);
                    indexReader.close();
                    if (selectedCluster == null) {
                        return "";

                    }
                    ClusterReader clusterReader = new ClusterReader();
                    clusterReader.open(clustId);
                    List<Index> indexs = clusterReader.getIndexes();
                    int dataSize = indexs.size();
                    clusterReader.close();
                    int i = 1;
                    browseIndexLabel.setText("Viewing Data in cluster-" + clustId + " ...");
                    browseIndexProgress.setValue(0);
                    for (Index index : indexs) {
                        ImageResult imageResult = new ImageResult();
                        imageResult.setPath(index.getFilePath());
                        imageResult.setSimilarity(selectedCluster.getDistance(index));
                        try {
                            BufferedImage bufferedImage = ImageIO.read(new File(index.getFilePath()));
                            imageResult.setBufferedImage(GraphicsUtilities.resizeImage(bufferedImage,
                            Constants.THUMB_WIDTH, Constants.THUMB_HEIGHT));
                            thumbIndexPanel.getListModel().add(imageResult);
                            browseIndexProgress.setValue(i * 100 / dataSize);
                        } catch (IOException ex) {
                        }
                        i++;
                    }
                    thumbIndexPanel.changePageButtonState();

                } catch (IOException ex) {
                    ex.printStackTrace();
                }

                return "";
            }

            @Override
            protected void done() {
                browseIndexLabel.setText("Done.");
                thumbIndexPanel.setEnabled(true);
                viewDataButton.setEnabled(true);
            }
        };

        browseWorker.execute();

    }//GEN-LAST:event_viewDataButtonActionPerformed

    private void numClusterComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numClusterComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numClusterComboActionPerformed

    int ex=11;
    int i=11;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        System.out.println("Insert Image Example!");
		String driverName = "com.mysql.jdbc.Driver";
		String url = "jdbc:mysql://localhost:3306/";
		String dbName = "test";
		String userName = "root";
		String password = "root";
		Connection con = null;

        //
        
       
        try {
        gender=String.valueOf(jComboBox1.getSelectedItem());
            //System.out.println(gender);
        hair=String.valueOf(jComboBox2.getSelectedItem());
        path=f.getAbsolutePath();
        System.out.println(path);
            Class.forName(driverName);
		   con = DriverManager.getConnection(url+dbName,userName,password);
		   Statement st = con.createStatement();
                   
                   //while(ex<10)
                   //{   
		   File imgfile = new File("C:\\Users\\Owner\\Desktop\\loadimg\\src\\ex"+ex+".jpg");
		  ex++;
		  FileInputStream fin = new FileInputStream(imgfile);
                  
                 PreparedStatement pre =
		   con.prepareStatement("insert into Image values(?,?,?,?)");
		 /*Scanner sn=new Scanner(System.in);
                    System.out.println("Gender"+i+":");
                    String gn=sn.next();
                    System.out.println("Hair"+i+":");
                    String hr=sn.next();*/
		   pre.setInt(1, i);
                   i++;
                   if(gender.equals("Male"))
                   {
		   pre.setInt(2,1);
                   }
                   else
                   {
                   pre.setInt(2,0);
                   }
                   if(hair.equals("Black"))
                   {
                     pre.setInt(3,1);  
                   }
                   else
                   {
                     pre.setInt(3,0);  
                   }
                   pre.setBinaryStream(4,(InputStream)fin,(int)imgfile.length());
		   pre.executeUpdate();
		   
                   System.out.println("Successfully inserted the file into the database!");

		   pre.close();
	         //}
                   con.close();

            
            /*rohit
            fis=new FileInputStream(path);

            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/test","root","root");
            PreparedStatement pstmt=con.prepareStatement("insert into image values(?,?,?,?)");
            pstmt.setInt(1,1);
            pstmt.setString(2,gender);
            pstmt.setString(3,hair);
            pstmt.setBinaryStream(4,fis,fis.available());
            pstmt.executeUpdate();
                  end*/
            
        }catch(Exception e)
        {
            System.err.println(e);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        imageChooser1.setFileFilter(new FileNameExtensionFilter("JPEG file", "jpg", "jpeg"));
        imageChooser1.setFileSelectionMode(JFileChooser.FILES_ONLY);
        imageChooser1.setDialogTitle("Open Query Image ...");
        imageChooser1.showDialog(this, "Open");
        f = imageChooser1.getSelectedFile();
        try {
            bufferedImage1 = ImageIO.read(imageChooser1.getSelectedFile());

            height= bufferedImage1.getHeight();
            width= bufferedImage1.getWidth();
            jLabel6.setSize(width,height);
            jLabel6.setIcon(new ImageIcon(bufferedImage1));

        } catch (IOException ex) {
            //Logger.getLogger(DemoJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* imagePathText.setText(f.getAbsolutePath());
        BufferedImage bufferedImage = ImageIO.read(imageChooser.getSelectedFile());
        bufferedImage = GraphicsUtilities.resizeImage(bufferedImage, 125, 140);
        imageLabel.setIcon(new ImageIcon(bufferedImage));
        */

        //checkInputSearch();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      System.out.println("Retrive Image Example!");
      gender1=String.valueOf(jComboBox3.getSelectedItem());
           
        hair1=String.valueOf(jComboBox4.getSelectedItem());
		String driverName = "com.mysql.jdbc.Driver";
		String url = "jdbc:mysql://localhost:3306/";
		String dbName = "test";
		String userName = "root";
		String password = "root";
		Connection con = null;
 
		try{
			Class.forName(driverName);
			con = DriverManager.getConnection(url+dbName,userName,password);
			Statement stmt = con.createStatement();
                        //Scanner sn=new Scanner(System.in);
                       //System.out.println("Which Gender images u want :");
                    //String gn=sn.next();
                    int k;
                    if(gender1.equals("Male"))
                    {
                        k=1;
                    }
                    else 
                    {
                        k=0;
                    }
                    //System.out.println("\nWhich hair color images u want :");
                    //String ha=sn.next();
                    int hk;
                    if(hair1.equals("Black"))
                    {
                        hk=1;
                    }
                    else 
                    {
                        hk=0;
                    }
                   
			ResultSet rs = stmt.executeQuery("select image from image where gender="+k+" and hair="+hk);
			int i = 0;
			while (rs.next()) {
				InputStream in = rs.getBinaryStream(1);
                              
                            //System.out.println("binary :"+rs.getByte("image"));
			//application.getRealPath("/") + "image/"	
                         //OutputStream f = new FileOutputStream(new File("test"+i+".jpg"));
                                OutputStream f = new FileOutputStream(new File("C:\\Users\\Owner\\Desktop\\outputimg\\"+"test"+i+".jpg"));
				i++;
                                int c;
                                //c = in.read();
                                //f.write(c);
				
				while ((c = in.read()) > -1) {
					f.write(c);
				}
                                System.out.println("retrieved sucessfully....");
				f.close();
				in.close();
			}
		}catch(Exception ex){
			System.out.println(ex.getMessage());
		}  

// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
  System.out.println("Delete Image Example!");
		String driverName = "com.mysql.jdbc.Driver";
		String url = "jdbc:mysql://localhost:3306/";
		String dbName = "test";
		String userName = "root";
		String password = "root";
		Connection con = null;
 
		try{
			Class.forName(driverName);
			con = DriverManager.getConnection(url+dbName,userName,password);
			Statement stmt = con.createStatement();
			int rs = stmt.executeUpdate("delete from image");
                               
                        System.out.println(rs);
			
                        System.out.println("\n"+rs+"Images deleted successfully");			
		    
                        
                        
		}catch(Exception ex){
			System.out.println(ex.getMessage());
		}
// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
       indexWorker = new SwingWorker<String, Void>() {

            String notes;

            @Override
            protected String doInBackground() throws Exception {
                //String add="C:\\Users\\Owner\\Desktop\\jcbir-src-20110109";
                //File folder=folderChooser.setCurrentDirectory("C:\\\\Users\\\\Owner\\\\Desktop\\\\jcbir-src-20110109");
                 File folder = folderChooser.getSelectedFile();
                // image filter masih nge-bug
                File[] files = folder.listFiles(new ImageFileFilter(false));
                //System.out.println(files.length);
                if (!folder.isDirectory() || folder == null || files.length == 0) {
                    notes = "FAIL";
                    return notes;
                }

                startIndexButton.setEnabled(false);
                viewDataButton.setEnabled(false);
                indexProgress.setStringPainted(true);
                time = System.currentTimeMillis();
                IndexWriter indexWriter = new IndexWriter();
                List<Index> indexes = new ArrayList<Index>();
                // feature extraction
                numIndex = 1;
                for (File f : files) {
                    try {
                        BufferedImage bufferedImage = ImageIO.read(f);
                        if (bufferedImage.getHeight(null) != Constants.IMAGE_HEIGHT
                                || bufferedImage.getWidth(null) != Constants.IMAGE_WIDTH) {
                            bufferedImage = GraphicsUtilities.resizeImage(bufferedImage,
                                    Constants.IMAGE_WIDTH, Constants.IMAGE_HEIGHT);
                        }
                        indexingStatusLabel.setText("Extracting image : " + f.getAbsolutePath());
                        Index index = indexWriter.getIndex(bufferedImage);
                        indexProgress.setValue(numIndex * 100 / files.length);
                        index.setFilePath(f.getAbsolutePath());
                        //indexWriter.addIndex(index);
                        indexes.add(index);
                        numIndex++;
                    } catch (IOException ex) {
                        ex.printStackTrace();
                    }
                }

                // k-means clustering
                KMeans kMeans = new KMeans();
                int maxIter = Integer.parseInt(maxIterText.getText());
                kMeans.setNumCluster(Integer.parseInt(numClusterCombo.getSelectedItem().toString()));
                kMeans.setMaxIteration(maxIter);
                indexingStatusLabel.setText("Clustering Indexs ....");
                indexProgress.setIndeterminate(true);
                kMeans.computeCluster(indexWriter, indexes);
                indexProgress.setIndeterminate(false);

                indexingStatusLabel.setText("Saving Indexs ....");
                // indexing ...
                Cluster[] clusters = kMeans.getClusters();
                // create root index
                indexWriter.open();
                for (Cluster c : clusters) {
                    indexWriter.addCluster(c);
                }
                indexWriter.close();


                //create clusters index
                numIndex = 1;
                ClusterWriter clusterWriter = new ClusterWriter();
                for (int idx = 0; idx < kMeans.getNumCluster(); idx++) {
                    clusterWriter.open(idx);
                    for (Index ix : clusters[idx].getMembers()) {
                        indexingStatusLabel.setText("Add image " + ix.getFilePath() + " to cluster-" + idx);
                        clusterWriter.addIndex(ix);
                        indexProgress.setValue(numIndex * 100 / files.length);
                        numIndex++;
                    }
                    clusterWriter.close();
                }

                notes = "SUCCESS";
                return notes;
            }

            @Override
            protected void done() {
                indexProgress.setValue(0);
                if ("FAIL".equals(notes)) {
                    indexingStatusLabel.setText("Can't Index images because path has no images");
                    browsePanel.setVisible(false);
                    return;
                }
                indexingStatusLabel.setText("Finished indexing " + (numIndex - 1) + " images in " + ((System.currentTimeMillis() - time) / 1000) + " s.");
                //enabled clustId combobox
                Integer clustSize = (Integer) numClusterCombo.getSelectedItem();
                Integer[] nums = new Integer[clustSize];
                for (int i = 0; i < clustSize; i++) {
                    nums[i] = i + 1;
                }

                thumbIndexPanel.getListModel().clear();
                clustIdComboBox.setModel(new DefaultComboBoxModel(nums));
                browsePanel.setVisible(true);
                //thumbIndexPanel.setVisible(false);
                startIndexButton.setEnabled(true);
                viewDataButton.setEnabled(true);
            }
        };

        indexWorker.execute();
        /**
        // TODO add your handling code here:
        ImageIndexer indexer = new ImageIndexer();
        startIndexButton.setEnabled(false);
        try {
        indexer.indexToDatabase(folderChooser.getSelectedFile(), !addCheck.isSelected());
        } catch (Exception e) {
        }
        startIndexButton.setEnabled(true);*/
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void checkInputSearch() {
        if (imageChooser.getSelectedFile() == null) {
            searchButton.setEnabled(false);
            return;
        }

        try {
            double a = Double.parseDouble(alphaText.getText());
            double b = Double.parseDouble(betaText.getText());
            if (a > 1 || a < 0 || b > 1 || b < 0) {
                searchButton.setEnabled(false);
                return;
            }

        } catch (NumberFormatException nfe) {
            searchButton.setEnabled(false);
            return;
        }

        searchButton.setEnabled(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                try {
                    LiquidLookAndFeel.setLiquidDecorations(true, "mac");
                    //LiquidLookAndFeel.setStipples(false);
                    LiquidLookAndFeel.setPanelTransparency(true);
                    javax.swing.UIManager.setLookAndFeel("com.birosoft.liquid.LiquidLookAndFeel");
                    //javax.swing.UIManager.setLookAndFeel("com.seaglasslookandfeel.SeaGlassLookAndFeel");

                    new MainFrame().setVisible(true);
                } catch (Exception e) {
                    e.printStackTrace();
                }


            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label Gender;
    private javax.swing.JPanel aboutTab;
    private javax.swing.JLabel alphaLabel1;
    private javax.swing.JTextField alphaText;
    private javax.swing.JLabel betaLabel1;
    private javax.swing.JTextField betaText;
    private javax.swing.JButton browseButton;
    private javax.swing.JButton browseFolderButton;
    private javax.swing.JLabel browseIndexLabel;
    private javax.swing.JProgressBar browseIndexProgress;
    private javax.swing.JPanel browsePanel;
    private javax.swing.JTabbedPane cbirTab;
    private javax.swing.JComboBox clustIdComboBox;
    private javax.swing.JPanel creditsPanel;
    private javax.swing.JPanel folderPanel;
    private javax.swing.JTextField folderText;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JTextField imagePathText;
    private javax.swing.JProgressBar indexProgress;
    private javax.swing.JLabel indexingStatusLabel;
    private javax.swing.JPanel indexingTab;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel luceneLabel1;
    private javax.swing.JLabel maxIterLabel;
    private javax.swing.JTextField maxIterText;
    private javax.swing.JComboBox numClusterCombo;
    private javax.swing.JLabel numClusterLabel;
    private javax.swing.JPanel progressPanel;
    private javax.swing.JPanel queryPanel;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JProgressBar searchProgress;
    private javax.swing.JPanel searchTab;
    private javax.swing.JLabel selectClusterLabel;
    private javax.swing.JButton startIndexButton;
    private javax.swing.JLabel statusLabel;
    private com.google.code.jcbir.gui.JThumbnailPanel thumbIndexPanel;
    private com.google.code.jcbir.gui.JThumbnailPanel thumbnailPanel;
    private javax.swing.JCheckBox useClusterCheck;
    private javax.swing.JButton viewDataButton;
    // End of variables declaration//GEN-END:variables
}
